yatube/about/urls.py
"""about URL Configuration."""

from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
"""URLs Configuration of the 'Posts' application."""

from django.urls import path

from posts import views

app_name = "posts"

urlpatterns = [
    path(
        "group/<slug:slug>/",
        views.group_posts,
        name="group_list",
    ),
    path(
        "profile/<str:username>/",
        views.profile,
        name="profile",
    ),
    path(
        "posts/<int:post_id>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "create/",
        views.post_create,
        name="post_create",
    ),
    path(
        "posts/<int:post_id>/edit/",
        views.post_edit,
        name="post_edit",
    ),
    path(
        "posts/<int:post_id>/comment/",
        views.add_comment,
        name="add_comment",
    ),
    path(
        "follow/",
        views.follow_index,
        name="follow_index",
    ),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
    path("", views.index, name="index"),
]

yatube/yatube/urls.py
"""yatube URL Configuration."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = "core.views.permission_denied"
handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/templates/includes/error_message.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/form_field.html
{% load user_filters %}
<div class="form-group row my-3 p-3"
     aria-required="{% if field.field.required %}true{% else %}false{% endif %}"
>
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}
      <span class="required text-danger">*</span>
    {% endif %}
  </label>
  <div>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small
        id="{{ field.id_for_label }}-help"
        class="form-text text-muted"
      >{{ field.help_text }}
      </small>
    {% endif %}
  </div>
</div>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img
          src="{% static 'img/logo.png' %}"
          width="30" height="30" class="d-inline-block align-top" alt=""
        >
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">
            <a
              class="nav-link
              {% if view_name == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}"
            >Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link
              {% if view_name == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}"
            >Технологии
            </a>
          </li>
          {% if user.username %}
            <li class="nav-item">
              <a
                class="nav-link
                {% if view_name == 'posts:post_create' %}active{% endif %}"
                href="{% url 'posts:post_create' %}"
              >Новая запись
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link link-light
                {% if view_name  == 'users:logout' %}active{% endif %}"
                href="{% url 'users:logout' %}"
              >Выйти
              </a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item">
              <a
                class="nav-link link-light
                {% if view_name  == 'users:login' %}active{% endif %}"
                href="{% url 'users:login' %}"
              >Войти
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link link-light
                {% if view_name  == 'users:signup' %}active{% endif %}"
                href="{% url 'users:signup' %}"
              >Регистрация
              </a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

yatube/templates/includes/post_card.html
{% load thumbnail %}
<article>
  <ul>
    <li>Автор: {{ post.author.get_full_name }}
      {% if post.author.get_full_name %}
        <a
          href="{% url 'posts:profile' post.author.username %}"
        >все посты пользователя
        </a>
      {% endif %}
    </li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaks }}</p>
  <a
    href="{% url 'posts:post_detail' post.id %}"
  >подробная информация
  </a>
</article>