yatube/about/urls.py
"""about URL Configuration."""

from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
"""URLs Configuration of the 'Posts' application."""

from django.urls import path

from posts import views

app_name = "posts"

urlpatterns = [
    path(
        "group/<slug:slug>/",
        views.group_posts,
        name="group_list",
    ),
    path(
        "profile/<str:username>/",
        views.profile,
        name="profile",
    ),
    path(
        "posts/<int:post_id>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "create/",
        views.post_create,
        name="post_create",
    ),
    path(
        "posts/<int:post_id>/edit/",
        views.post_edit,
        name="post_edit",
    ),
    path(
        "posts/<int:post_id>/comment/",
        views.add_comment,
        name="add_comment",
    ),
    path(
        "follow/",
        views.follow_index,
        name="follow_index",
    ),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
    path("", views.index, name="index"),
]

yatube/yatube/urls.py
"""yatube URL Configuration."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = "core.views.permission_denied"
handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
"""Database settings of the 'Posts' application."""

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Table settings for groups of user posts."""

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    """Table settings for user posts."""

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
    )
    image = models.ImageField(
        upload_to="posts/",
        blank=True,
    )

    def __str__(self):
        return self.text[: settings.NUM_CHAR]

    class Meta:
        ordering = ["-pub_date"]


class Comment(models.Model):
    """Table settings for post comment."""

    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
    )

    def __str__(self):
        return self.text[: settings.NUM_CHAR]


class Follow(models.Model):
    """Table settings for user subscriptions."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follow"
            ),
        ]

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {
            "text": "Текст поста",
            "group": "Группа",
            "image": "Картинка",
        }
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }

    def clean_text(self):
        data = self.cleaned_data["text"]
        if not data:
            raise forms.ValidationError("Заполните поле для текста записи")
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

    def clean_text(self):
        data = self.cleaned_data["text"]
        if not data:
            raise forms.ValidationError(
                "Заполните поле для текста комментария"
            )
        return data

yatube/posts/views.py
"""URLs request handlers of the 'Posts' application."""

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User
from posts.utils import paginator_func


@cache_page(settings.CACHE_TIME, key_prefix="index_page")
def index(request):
    """Main page."""
    post_list = Post.objects.select_related("group", "author")
    page_obj = paginator_func(request, post_list)
    context = {
        "page_obj": page_obj,
        "index": True,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    """Page of user posts filtered by groups."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related("group", "author")
    page_obj = paginator_func(request, post_list)
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    """Page of user profile."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related("group", "author")
    page_obj = paginator_func(request, post_list)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {
        "author": author,
        "page_obj": page_obj,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    """Page of single post."""
    post = get_object_or_404(
        Post.objects.select_related("group", "author"), id=post_id
    )
    form = CommentForm()
    comments = post.comments.select_related("author")
    context = {
        "post": post,
        "form": form,
        "comments": comments,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    """Page for adding a new post."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {"form": form}
    if not form.is_valid():
        return render(request, "posts/create_post.html", context)
    form.instance.author = request.user
    form.save()
    return redirect("posts:profile", username=request.user.username)


@login_required
def post_edit(request, post_id):
    """Post editing pages."""
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    context = {
        "form": form,
        "is_edit": True,
    }
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id=post_id)
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    """Creating a comment to the post."""
    form = CommentForm(request.POST or None)
    if form.is_valid():
        form.instance.author = request.user
        form.instance.post = get_object_or_404(Post, id=post_id)
        form.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    """Posts of authors to which the user is subscribed."""
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_func(request, post_list)
    context = {
        "page_obj": page_obj,
        "follow": True,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    """Subscribe to the author."""
    if request.user.username != username:
        follow_author = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(user=request.user, author=follow_author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    """Unsubscribe from the author."""
    unfollow_author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=unfollow_author).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block head_title %}
  {% if is_edit %}Редактировать запись{% else %}Новый пост{% endif %}
{% endblock %}
{% block title %}
  {% if is_edit %}Редактировать запись{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/error_message.html' %}
          <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {% for field in form %}
              {% include 'includes/form_field.html' %}
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block head_title %}
  Посты авторов из ваших подписок
{% endblock %}
{% block title %}
  Посты авторов из ваших подписок
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
    {% if post.group %}
      <a
        href="{% url 'posts:group_list' post.group.slug %}"
      >все записи группы: {{ post.group.title }}
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block head_title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block head_title %}
  Последние обновления на сайте
{% endblock %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
    {% if post.group %}
      <a
        href="{% url 'posts:group_list' post.group.slug %}"
      >все записи группы: {{ post.group.title }}
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block head_title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li
          class="list-group-item"
        >Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li
            class="list-group-item"
          >Группа: {{ post.group.title }}<br>
            <a
              href="{% url 'posts:group_list' post.group.slug %}"
            >все записи группы
            </a>
          </li>
        {% endif %}
        <li
          class="list-group-item"
        >Автор: {{ post.author.get_full_name }}
        </li>
        <li
          class="list-group-item d-flex
          justify-content-between
          align-items-center"
        >Всего постов автора: <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a
            href="{% url 'posts:profile' post.author.get_username %}"
          >все посты пользователя:<br>{{ post.author.get_username }}
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      {% if post.author.username == user.username %}
        <a
          class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}"
        >редактировать запись
        </a>
      {% endif %}
    </article>
  </div>
  {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
  {% endif %}
  {% if comments %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block head_title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block title %}
  Все посты пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if user.username != author.username %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >Подписаться
      </a>
    {% endif %}
  {% endif %}
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
    {% if post.group %}
      <a
        href="{% url 'posts:group_list' post.group.slug %}"
      >все записи группы: {{ post.group.title }}
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}